version: "3.8"
services:
  backend:
    build: ./replichain-backend
    ports:
      - "5000:5000"
    env_file:
      - ./replichain-backend/.env

  frontend:
    build: ./replichain-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
